const ADD_TABS = "ADD_TABS",
  REMOVE_TABS = "REMOVE_TABS",
  EDIT_TABS = "EDIT_TABS",
  TOGGLE_STATE = "TOGGLE_STATE",
  LOGIN_IN = "LOGIN_IN"

export default {
  ADD_TABS,
  REMOVE_TABS,
  EDIT_TABS,
  TOGGLE_STATE,
  LOGIN_IN
};